---
- debug: msg="installing MariaDB version {{ mariadb_version_major }}"

- include: redhat/install.yml
  when: ansible_os_family == 'RedHat'

- include: debian/install.yml
  when: ansible_os_family == 'Debian'
