---
- name: load the os specific variables
  include_vars: "{{ ansible_os_family | lower }}/default.yml"

- include: install.yml

- include: tokudb.yml
  when: mariadb_tokudb_install

- include: configure.yml
  when: mariadb_configure

- include: secure.yml
- include: databases.yml
- include: users.yml
