---
# file: mariadb/tasks/main.yml

- include: vars.yml

- include: install.yml

- include: tokudb.yml
  when: mariadb_tokudb_install

- include: configure.yml
  when: mariadb_configure

- include: secure.yml
- include: databases.yml
- include: users.yml
