# file: mysql/vars/redhat/default.yml

mysql_packages:
  - mariadb
  - mariadb-server
  - MySQL-python

mysql_service_name: mariadb

mysql_cnf_path: /etc/my.cnf

mysql_sock_file: /var/lib/mysql/mysql.sock
