# file: mysql/vars/redhat/default.yml

mariadb_packages:
  - mariadb
  - mariadb-server
  - MySQL-python

mariadb_service_name: mariadb

mariadb_cnf_path: /etc/my.cnf

mariadb_sock_file: /var/lib/mysql/mysql.sock
